---
# This playbook will setup a docker-ized content host deployment
# environment on the target system(s). To run this:
# - Make sure you are in sat6helper/dev/playbooks directory and run
# - # ansible-playbook -i hosts chd-setup.yaml
#
# After completion, a RHEL 7.4 docker image will be available
# and the git repo will be located at /root/content-host-d
- hosts: home
  remote_user: root
  tasks:
  - name: Install Docker
    package: name=docker state=latest
  - service: name=docker state=started enabled=yes

  - name: Install python pip
    easy_install: name=pip
  - name: Install docker-py
    pip: name=docker-py state=latest

  - name: Install git
    package: name=git state=present
  - name: Clone content host repo
    git:
      repo : https://github.com/JacobCallahan/content-host-d.git
      version : master
      dest : /root/content-host-d

  - name: Build RHEL 7 content host image
    docker_image:
      path: /root/content-host-d/RHEL7/
      name: ch-d
      tag: rhel7
